### PR TITLE
FromGeneric wrapper for use with DerivingVia

### PR DESCRIPTION
**Pull request by torgeirsh**
I experimented with making a FromGeneric newtype wrapper for use with DerivingVia, inspired by TextShow.Generic.FromGeneric in text-show. I don't know if this is the right module for it, or if it's even acceptable to change the signatures of the Witherable members, or to use recent extensions like QuantifiedConstraints. See [QuantifiedConstraints and the trouble with Traversable](https://ryanglscott.github.io/2018/06/22/quantifiedconstraints-and-the-trouble-with-traversable/) for more information. Maybe there's a better way to do this?

Here's how to use it:
```
data Example a = Example {
    someNumber :: Int,
    things :: [a]
} deriving (Functor, Foldable, Traversable, Generic1) deriving Filterable via FromGeneric Example

deriving via FromGeneric Example instance Witherable Example
```
I could only get it to compile with the Witherable instance standalone for some reason.

### CODE REVIEW

**Comment by fumieval** [comment]
Adding `Representational1 m` will break almost all code parameterised by `Witherable`. The `mapTraverse` approach seems more promising - it does mean a breaking change to the `Witherable` class, but only affects those who have own instances.

Instead of adding `FromGeneric` to this package, we could use `Generically` from `generic-data`. `https://hackage.haskell.org/package/generic-data-0.9.1.0/docs/Generic-Data.html#t:Generically`.

**Comment by torgeirsh** [comment]
Do you mean to change wither to a similarly adjusted mapWither? It sounds quite disruptive as well. Maybe a Witherable instance for Generic is a too tall order for the current ecosystem...

**Comment by fumieval** [comment]
IMO adding `Representational1 m` is not feasible because we have to change all the polymorphic use sites. We could add `mapWither` now, deprecating `wither`. It doesn't seem worth the breakage though... (especially when newtype-deriving Traversable has the same problem).

**Comment by torgeirsh** [comment]
I agree, mapWither isn't worth the breakage, especially since it's a workaround for a more fundamental problem. Thanks for the input!

**Comment by treeowl** [comment]
@torgeirsh, it's not *just* a workaround. For "expensive" functors and short traversals, it can offer performance-significant fusion opportunities.

**Comment by fumieval** [comment]
[Class method deprecation](https://gitlab.haskell.org/ghc/ghc/-/issues/10071) would help migration, however I'm not sure what the status of this ticket is

**Comment by treeowl** [comment]
Bleh, I guess we can keep it closed for now, with sadness

**Comment by fumieval** [comment]
To be clear the mapWither approach does seem promising. I'll try to bring them in slowly

**Pull request closed without merging**
