### PR TITLE
Add Filterable instance for MonoidalMap

### PR DESCRIPTION
**Pull request by ali-abrar**

### CODE REVIEW

**Comment by phadej** [comment]
I'm late with this, but in general simpler to make "data-type" packages depend on "type-class" packages.

With this addition `witherable` grew its dependency footprint considerably, where if `monoidal-containers` would depended on `witherable` the addition would been minimal.

This results in fact that adding `witherable` as dependency to other packages has a higher cost.

**Comment by fumieval** [comment]
Hmm I didn't realise that it depends on lens... Although being a fan-made package, witherable has [more reverse dependencies](https://packdeps.haskellers.com/reverse/witherable) so it seems reasonable to move the instance into `monoidal-containers`

**Comment by ali-abrar** [comment]
It looks like witherable depends on lens anyway in version 0.3.3. Does that change the analysis at all?

**Comment by fumieval** [comment]
There was no feedback on https://github.com/bgamari/monoidal-containers/issues/49 so I gave up on this.

**Pull request merged**
