### PR TITLE
Removing deprecated modules and packages

### PR DESCRIPTION
**Pull request by jcranch**
As things are, this repository contains three different variants of the same code providing the same functionality (across two packages). Two have been deprecated for at least three years. The presence of these two deprecated versions makes the package less appealing and harder to interact with (both on GitHub, and on Hackage).

There is an argument that the best location for this library is `Data.Witherable`, not `Witherable` (by analogy with `Data.{Foldable,Traversable,Functor}`). However, I think the best way to do this is in two parts: get down to one single package with one single module now, and then (maybe later) talk about what that one module should be called.

### CODE REVIEW

**Comment by phadej** [comment]
This (removal of a module from `witherable`) is a breaking change.  I don't think it's worth doing if there aren't anything else (breaking) happening.

**Comment by jcranch** [comment]
Pull request #93 is also a breaking change. My pull request is perhaps not the only way of solving the problem, but it is a problem that must be solved, and I don't think it can be solved without a breaking change.

**Comment by phadej** [comment]
#93 can be solver in non-breaking change by removing the incorrect (?) law.

**Comment by fumieval** [comment]
For the record I'm +1 to the change. After 10+ years of using Haskell in both hobby and production, I concluded that module name prefixes don't worth it

**Comment by phadej** [comment]
@fumieval sure. And #94 is a good reason to do breaking change (and cleanup). But I'm quite sure people won't like #93, so that should be considered carefully.

**Comment by phadej** [comment]
witherable-class removed in #98, and `Data.Witherable` in #99. Thanks for prompting the cleanups.

**Pull request closed without merging**
