### PR TITLE
Make witherM for List a good consumer for fusion

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
I've not actually tested this.

**Comment by treeowl** [comment]
`foldrM` doesn't necessarily seem like the most sensible thing for lists. I think the place to start is `wither`:

```haskell
wither f = foldr go (pure []) where
    go x r = liftA2 (maybe id (:)) (f x) r
```

The default `witherM` shouldn't be terrible, but it might be worth experimenting with

```haskell
witherM f = foldr go (pure []) where
    go x r = f x >>= \case
      Nothing -> r
      Just y -> ((:) y) <$> r
```

**Comment by treeowl** [comment]
Yes, that's looking much better. Please rebaae.

**Comment by andrewthad** [comment]
I've got a [gist demonstrating that this works](https://gist.github.com/andrewthad/c1bca65dbf002921c328beaca96e6489). Sadly, GitHub alphabetizes the two files, so core shows up before source Haskell. Interestingly, `witherM` leads to slightly better core than `wither` does. This can be observed by swapping out `witherM` for `wither` in the example code I linked to. Squashing and rebasing now.

**Comment by fumieval** [comment]
Looks good, thanks

**Pull request merged**
