### PR TITLE
Add emptiness properties

### LINKED ISSUE #58: Document a consequence of the laws
There's an intuitively obvious law that follows from the `Filterable` laws in a way I found less than obvious.

### Law

Suppose that `xs :: f a` and that for all `b :: Type` and all `f, g :: a -> b`, `fmap f xs = fmap g xs` (that is, `xs` does not actually "contain" any `a` values). Then for all `c :: Type` and all `h, i :: a -> Maybe c`, `mapMaybe h xs = mapMaybe i xs`. Letting `h` be `Just` leads to a nice corollary about `filter`.

### Proof

Suppose that for all `b :: Type` and all `f, g :: a -> b`, `fmap f xs = fmap g xs`.

Then by the preservation law, for all `f,g :: a -> b`,
`mapMaybe (Just . f) xs = mapMaybe (Just . g) xs`

Therefore, for all `c :: Type` and all `h, i :: a -> Maybe c`,

`mapMaybe id . mapMaybe (Just . h) $ xs = mapMaybe id . mapMaybe (Just . i) $ xs`

By the composition law,

`mapMaybe h xs = mapMaybe i xs`.

I imagine we can prove a similar theorem about `wither`.

### PR DESCRIPTION
**Pull request by treeowl**
Closes #58

### CODE REVIEW

**Comment by treeowl** [comment]
I'd like to bring this around to `null` in the last section, but I haven't had a chance to work through that in detail.

**Comment by alexfmpe** [comment]
I personally feel a more intuitive direction (provided all steps are equivalences - I haven't actually verified this is the case) would be to start by defining 'empty' in terms of `Filterable` as any element `e` such that `forall f :: a -> Maybe a. e = mapMaybe f e`, which trivially gives `mapMaybe f e = e = mapMaybe g e`, then work backwards until we reach `fmap f e = fmap g e`.

**Comment by alexfmpe** [comment]
> I'd like to bring this around to null in the last section, but I haven't had a chance to work through that in detail.
Tricky. What does this mean for types that are `Filterable` but not `Foldable` ? (e.g. The `Event` type from FRP)

**Comment by treeowl** [comment]
> > I'd like to bring this around to null in the last section, but I haven't had a chance to work through that in detail.
> 
> Tricky. What does this mean for types that are `Filterable` but not `Foldable` ? (e.g. The `Event` type from FRP)

That would only apply to `Witherable`, not `Filterable`. I disagree with you about the correct starting point, but it would be nice to prove an equivalence if there is one.

**Comment by treeowl** [comment]
> I personally feel a more intuitive direction (provided all steps are equivalences - I haven't actually verified this is the case) would be to start by defining 'empty' in terms of `Filterable` as any element `e` such that `forall f :: a -> Maybe a. e = mapMaybe f e`, which trivially gives `mapMaybe h e = e = mapMaybe i e`, then work backwards until we reach `fmap f e = fmap g e`.

To me, `forall b (f :: a -> b). fmap f e = fmap g e` is a more intuitive notion of emptiness, as well as a more general one, since it makes sense for general `Functor` instances.

You write that we trivially get `mapMaybe h e = e = mapMaybe i e`, but that doesn't look too trivial to me, because `h` and `i` may not have types that look like `a -> Maybe a`! I do suspect there's an equivalence, but it may require some monkeying around with parametricity to get there. The furthest we could try to go in that direction is to prove that if `filter p xs = xs` for all `p`, then `xs` is empty.

**Comment by alexfmpe** [comment]
> To me, forall b (f :: a -> b). fmap f e = fmap g e is a more intuitive notion of emptiness, as well as a more general one, since it makes sense for general Functor instances.

I see. Yes, I agree that `Functor`'s view of 'emptiness' is a better starting point than `Filterable`'s view. 
I wasn't immediately convinced that `fmap f e = fmap g e` represented 'emptiness', but I'm having trouble coming up with any argument or counterexample. 

> You write that we trivially get mapMaybe h e = e = mapMaybe i e, but that doesn't look too trivial to me, because h and i may not have types that look like a -> Maybe a! 

Oops, messed up both the quantifiers and in reasoning. It does trivially mean that for `h, i :: a -> Maybe a` but as you say we want `a -> Maybe b`.

**Comment by alexfmpe** [comment]
> I wasn't immediately convinced that fmap f e = fmap g e represented 'emptiness', but I'm having trouble coming up with any argument or counterexample.

Ok I'm much more convinced.
Assuming `fmap f . toList = toList . fmap f` (which I believe holds by parametricity, but don't actually know how to prove):

```
forall f, g, h :: a -> b

fmap f xs = fmap g xs
=> toList (fmap f xs) = toList (fmap g xs)
=> fmap f (toList xs) = fmap g (toList xs)
=> catMaybes $ fmap f (toList xs) = catMaybes $ fmap g (toList xs)
=> mapMaybe f (toList xs) = mapMaybe g (toList xs)
=> forall h :: a->b. mapMaybe h (toList xs) = toList xs
=> mapMaybe (const Nothing) (toList xs) = toList xs
=> [] = toList xs
```

**Comment by alexfmpe** [comment]
Hmm, assuming `null = null . toList`, we could continue with
```
[] = toList xs
null [] = null (toList xs)
null [] = null xs
True = null xs
```

**Comment by treeowl** [comment]
The definition of `null` I'd prefer to deal with is

```haskell
null = getAll . foldMap (const (All False))
```

I imagine this can be proved equivalent to the default by elementary techniques, but I'm not sure.

For empty `e`, Theorem 3 proves (via `foldMapDefault`) that

```haskell
  null e
= getAll . foldMap (const (All False)) $ e
= getAll . foldMap (const (All True)) $ e
```

Because `All True = mempty`, `const (All True)` is a (trivial) monoid morphism. So by naturality,

```haskell
getAll . foldMap (const (All True))
= getAll . foldMap (const (All True) . const ())
= getAll . const (All True) . foldMap (const ())
= const True
```

(This last bit just proves the simple fact that `all (const True) = const True )`.

Substituting that result in shows that `null e = True`.

**Comment by treeowl** [comment]
The to backwards implications I don't know how to prove:

1. If `null e = True`, then `e` is empty.
2. If `filter (const False) e = e`, then `e` is empty.

These would be very nice to add.

**Comment by treeowl** [comment]
3. If `x ≠ y` and `x <$ e = y <$ e`, then `e` is empty.

**Comment by alexfmpe** [comment]
If we can prove the following (probably by parametricity)

```haskell
null . toList = null
toList . catMaybes = catMaybes . toList
fmap f . toList = toList . fmap f
fmap f e = fmap g e <=> fmap f (toList e) = fmap g (toList e)
```
then we have
```haskell
    toList e = []
<=> forall h i. fmap h (toList e) = fmap i (toList e)
<=> forall h i. fmap h e = fmap i e
```

1)
```haskell
    null e = True 
<=> null (toList e) = True
<=> toList e = []
```

2)
```haskell
    filter (const False) e = e
<=> mapMaybe (const Nothing) e = e
<=> catMaybes $ fmap (const Nothing) e = e
<=> catMaybes $ fmap (const Nothing) e = fmap id e
<=> catMaybes $ fmap (const Nothing) (toList e) = fmap id (toList e)
<=> mapMaybe (const Nothing) (toList e) = fmap id (toList e)
<=> [] = toList e
```

3)
```haskell
    x <$ e = y <$ e
<=> fmap (const x) e = fmap (const y) e
<=> fmap (const x) (toList e) = fmap (const y) (toList e)
<=> x <$ toList e = y <$ toList e
<=> toList e = []
```

**Comment by treeowl** [comment]
`fmap f e = fmap g e <=> fmap f (toList e) = fmap g (toList e)` certainly does not hold. `toList` loses information in most cases. Consider two maps whose values are the same (and occur in the same order) but whose keys are different.

**Comment by alexfmpe** [comment]
If `fmap f . toList = toList . fmap f` holds, then 
```haskell
toList (fmap f e) = toList (fmap g e) <=> fmap f (toList e) = fmap g (toList e)
```
so we can look instead at 
```haskell
fmap f e = fmap g e <=> toList (fmap f e) = toList (fmap g e)
```

Left-to-right implication is trivial (just apply `toList` on both sides), while right-to-left means something along the lines of "when we line up all the values and compare them pointwise after applying 2 different functions, if they are equal, the structures after mapping must have been equal", which seems plausible enough because `fmap` can't interact with the structure/context so we get `e`'s in both sides. I don't actually know how to prove this handwaving though.

> fmap f e = fmap g e <=> fmap f (toList e) = fmap g (toList e) certainly does not hold. toList loses information in most cases. Consider two maps whose values are the same (and occur in the same order) but whose keys are different.

I'm not sure that applies here because we're talking about two functions being mapped to the same value, not the same function mapped to two values, whichwould not hold:
`fmap f e1 = fmap f e2 => toList (fmap f e1) = toList (fmap f e2)` but the converse is blatantly false as you said.

**Comment by fumieval** [comment]
Makes sense to me

**Pull request merged**
